### ISSUE TITLE
cant run docker-compose build

### ISSUE THREAD

**Issue by obsd-guru** [f3-factory/fatfree-dev#1]
hi
when i try to run the docker-compose build command i just get this : 

`markus@t400:~/work/phptest/fatfree-dev$ docker-compose build

ERROR: The Compose file './docker-compose.yml' is invalid because:

Unsupported config option for networks: 'internal'

Unsupported config option for x-php-template: 'networks'

Unsupported config option for services: 'pgsql'

markus@t400:~/work/phptest/fatfree-dev$ docker-compose -v

docker-compose version 1.21.0, build unknown

markus@t400:~/work/phptest/fatfree-dev$
`

maybe my version of docker-compose is incompatible ? shouldt the whole compose file start with a "version: 'X.Y'" ? well i dont know but any help is most appreciated

regards

**Comment by ikkez** [comment]
Update your docker / docker-compose... I have docker v20.10 and docker-compose 1.29.2.

The **version: X.Y** in compose files is deprecated and not used anymore.

**Comment by obsd-guru** [comment]
Hi ikkez, 
thanks for the fast reply. u where totally right. my docker-compose was too old. runs now just fine.  and thanks for pointing out that version isnt used anymore (that shows how long i havent used it ;) )
